modLoader="javafml" #mandatory
loaderVersion="[28.1]" #mandatory. 26 for 1.14.2, 27 for 1.14.3
credits="Rewind" #optional
[[mods]] #mandatory
modId="ldskyblock" #mandatory
version="1.0" #mandatory
displayName="LD Skyblock" #mandatory
description='''
A Skyblock mod developed for Ludum Dare 45.
'''